# Site settings
title: Modern Blog3
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://w3synack.github.io" # the base hostname & protocol for your site
